// Code generated by gioui.org/cpu/cmd/compile DO NOT EDIT.

package piet

import "gioui.org/cpu"

var BinningProgramInfo *cpu.ProgramInfo

type BinningDescriptorSetLayout struct{}

const BinningHash = ""

func (l *BinningDescriptorSetLayout) Binding0() *cpu.BufferDescriptor {
	panic("unsupported")
}

func (l *BinningDescriptorSetLayout) Binding1() *cpu.BufferDescriptor {
	panic("unsupported")
}
