// Code generated by gioui.org/cpu/cmd/compile DO NOT EDIT.

package piet

import "gioui.org/cpu"

var CoarseProgramInfo *cpu.ProgramInfo

type CoarseDescriptorSetLayout struct{}

const CoarseHash = ""

func (l *CoarseDescriptorSetLayout) Binding0() *cpu.BufferDescriptor {
	panic("unsupported")
}

func (l *CoarseDescriptorSetLayout) Binding1() *cpu.BufferDescriptor {
	panic("unsupported")
}
