// Code generated by gioui.org/cpu/cmd/compile DO NOT EDIT.

package piet

import "gioui.org/cpu"

var ElementsProgramInfo *cpu.ProgramInfo

type ElementsDescriptorSetLayout struct{}

const ElementsHash = ""

func (l *ElementsDescriptorSetLayout) Binding0() *cpu.BufferDescriptor {
	panic("unsupported")
}

func (l *ElementsDescriptorSetLayout) Binding1() *cpu.BufferDescriptor {
	panic("unsupported")
}

func (l *ElementsDescriptorSetLayout) Binding2() *cpu.BufferDescriptor {
	panic("unsupported")
}

func (l *ElementsDescriptorSetLayout) Binding3() *cpu.BufferDescriptor {
	panic("unsupported")
}
