// Code generated by gioui.org/cpu/cmd/compile DO NOT EDIT.

package piet

import "gioui.org/cpu"

var Path_coarseProgramInfo *cpu.ProgramInfo

type Path_coarseDescriptorSetLayout struct{}

const Path_coarseHash = ""

func (l *Path_coarseDescriptorSetLayout) Binding0() *cpu.BufferDescriptor {
	panic("unsupported")
}

func (l *Path_coarseDescriptorSetLayout) Binding1() *cpu.BufferDescriptor {
	panic("unsupported")
}
