// Code generated by gioui.org/cpu/cmd/compile DO NOT EDIT.

package piet

import "gioui.org/cpu"

var Tile_allocProgramInfo *cpu.ProgramInfo

type Tile_allocDescriptorSetLayout struct{}

const Tile_allocHash = ""

func (l *Tile_allocDescriptorSetLayout) Binding0() *cpu.BufferDescriptor {
	panic("unsupported")
}

func (l *Tile_allocDescriptorSetLayout) Binding1() *cpu.BufferDescriptor {
	panic("unsupported")
}
